# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newlogin_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 868)
        MainWindow.setMouseTracking(True)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 50, 500, 700))
        self.label.setMinimumSize(QtCore.QSize(500, 700))
        self.label.setStyleSheet("border-image:url(:/img/ui_img/background.jpg);\n"
"border-radius:30px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 50, 500, 700))
        self.label_2.setMinimumSize(QtCore.QSize(500, 700))
        self.label_2.setStyleSheet("background-color: rgba(75, 75, 75, 200);\n"
"border-radius:30px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 160, 251, 61))
        self.label_3.setMinimumSize(QtCore.QSize(251, 61))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        font.setPointSize(25)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_3.setObjectName("label_3")
        self.edit_username = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_username.setGeometry(QtCore.QRect(220, 280, 351, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.edit_username.setFont(font)
        self.edit_username.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(255,255,255,200);\n"
"color:rgb(255, 255, 255)")
        self.edit_username.setText("")
        self.edit_username.setObjectName("edit_username")
        self.edit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_password.setGeometry(QtCore.QRect(220, 380, 351, 71))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.edit_password.setFont(font)
        self.edit_password.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(255,255,255,200);\n"
"color:rgb(255, 255, 255)")
        self.edit_password.setText("")
        self.edit_password.setObjectName("edit_password")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(220, 490, 105, 22))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(9)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("color:rgb(255, 255, 255)")
        self.checkBox.setObjectName("checkBox")
        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(280, 550, 241, 71))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_login.setFont(font)
        self.btn_login.setStyleSheet("QPushButton#btn_login{\n"
"background-color:rgb(153,0,0);\n"
"color:rgba(255,255,255);\n"
"border-radius:15px;\n"
"}\n"
"QPushButton#btn_login:pressed{\n"
"padding-top:7px;\n"
"padding-left:7px\n"
"}")
        self.btn_login.setObjectName("btn_login")
        self.btn_register = QtWidgets.QPushButton(self.centralwidget)
        self.btn_register.setGeometry(QtCore.QRect(510, 690, 121, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_register.setFont(font)
        self.btn_register.setStyleSheet("QPushButton#btn_register{\n"
"background-color:rgb(85, 85, 127);\n"
"color:rgba(255,255,255);\n"
"border-radius:15px;\n"
"}\n"
"QPushButton#btn_register:pressed{\n"
"padding-top:7px;\n"
"padding-left:7px\n"
"}")
        self.btn_register.setObjectName("btn_register")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(591, 70, 41, 34))
        self.pushButton.setStyleSheet("background-color:rgb(255,255,255,0);")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/ui_img/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.label.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=0, yOffset=0))
        self.label_2.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=0, yOffset=0))
        self.btn_login.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=3, yOffset=3))
        self.btn_register.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=3, yOffset=3))
        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "欢迎登录"))
        self.edit_username.setPlaceholderText(_translate("MainWindow", "账号："))
        self.edit_password.setPlaceholderText(_translate("MainWindow", "密码："))
        self.checkBox.setText(_translate("MainWindow", "记住密码"))
        self.btn_login.setText(_translate("MainWindow", "登录"))
        self.btn_register.setText(_translate("MainWindow", "注册"))
import loginapprcc

