# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newregiste_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(670, 658)
        Dialog.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Dialog.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(130, 120, 400, 400))
        self.label.setMinimumSize(QtCore.QSize(400, 400))
        self.label.setMaximumSize(QtCore.QSize(400, 400))
        self.label.setStyleSheet("border-image:url(:/img/ui_img/rebackground.jpg);\n"
"border-radius:30px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(130, 120, 400, 400))
        self.label_2.setMinimumSize(QtCore.QSize(400, 400))
        self.label_2.setMaximumSize(QtCore.QSize(400, 400))
        self.label_2.setStyleSheet("background-color: rgba(75, 75, 75, 200);\n"
"border-radius:30px;\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(270, 180, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(190, 260, 291, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setStyleSheet("color:rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.edit_username = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.edit_username.setMinimumSize(QtCore.QSize(0, 30))
        self.edit_username.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:1px solid rgb(255, 255, 255);\n"
"color:rgb(255,255,255)\n"
"\n"
"")
        self.edit_username.setObjectName("edit_username")
        self.horizontalLayout.addWidget(self.edit_username)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(190, 330, 291, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_5.setStyleSheet("color:rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.edit_password = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.edit_password.setMinimumSize(QtCore.QSize(0, 30))
        self.edit_password.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:1px solid rgb(255, 255, 255);\n"
"color:rgb(255,255,255)\n"
"\n"
"")
        self.edit_password.setObjectName("edit_password")
        self.horizontalLayout_2.addWidget(self.edit_password)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(210, 400, 261, 71))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_regiser = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_regiser.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_regiser.setFont(font)
        self.pushButton_regiser.setStyleSheet("QPushButton{\n"
"background-color:rgb(170, 0, 255);\n"
"color:rgb(255,255,255);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:7px;\n"
"padding-left:7px\n"
"}")
        self.pushButton_regiser.setObjectName("pushButton_regiser")
        self.horizontalLayout_3.addWidget(self.pushButton_regiser)
        self.pushButton_cancer = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_cancer.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_cancer.setFont(font)
        self.pushButton_cancer.setStyleSheet("QPushButton{\n"
"background-color:rgb(0, 170, 255);\n"
"color:rgb(255,255,255);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:7px;\n"
"padding-left:7px\n"
"}")
        self.pushButton_cancer.setObjectName("pushButton_cancer")
        self.horizontalLayout_3.addWidget(self.pushButton_cancer)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(461, 140, 61, 34))
        self.pushButton.setStyleSheet("background-color:rgb(255,255,255,0);")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/ui_img/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(Dialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "账号注册"))
        self.label_4.setText(_translate("Dialog", "账号"))
        self.label_5.setText(_translate("Dialog", "密码"))
        self.pushButton_regiser.setText(_translate("Dialog", "注册"))
        self.pushButton_cancer.setText(_translate("Dialog", "取消"))
import loginapprcc
